### ISSUE TITLE
Ордер на 0.01 акции

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Copyer#13]
Есть AxiTrader, который разрешает дробные лоты для акций. Оно бы и х с ним, но для Mohamed Jami Gaffoor на мастере AxiTrader-US03-Demo открывается 0.01 S&P, а на слейве AxiTrader-US07-Live и в логе - 0.02 S&P. Недоволен, гад. 

На этих счетах воспроизводится. Это я демо открыл. Можно пробовать на Rybas MT4 2. На терминале мастера открываешь 0.01 s&p.sf - на копировщике видишь 0.02
AxiTrader-US03-Demo
Login	20562277
Password 24VKCgWr22

AxiTrader-US03-Demo
Login	20562281
Password 2wri8E5j24

**Comment by JuliviMig** [comment]
не  воспр.  надо   у  него  взять  основной  пароль на  мастер  и  слейв. Открою  пару  отложенных - если  воспроизведется - исправлю

**Comment by JuliviMig** [comment]
причина - маленький  объем  контракта (50).  Поменял  тип  хранения  объема  с  целого  на плавающий.  Проверил - работает, но  может  стрельнуть  где  угодно
