### ISSUE TITLE
Импорт слейвов

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Copyer#15]
Импорт слейвов заносит 2 строки и вылетает Index out of bounds
файл на 10 счетов Andrew 1_slave.xls
[Andrew 1_slave.zip](https://github.com/JuliviMig/BJF_Copyer/files/1579350/Andrew.1_slave.zip)

**Comment by JuliviMig** [comment]
старый  формат транспортного  файла. Сделал  поддержку
