### ISSUE TITLE
Лог для GTX (FIX)

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Copyer#18]
На закрывающем ордере стоит Open copy order, и в строке мастера Sell, в строке слейва - Buy. 

См. скриншот.  В таблице выбрана строка, где открытие пачки ордеров Sell закончилось, и начинается закрытие.

![sell-buy](https://user-images.githubusercontent.com/26895847/34520367-643d2a66-f099-11e7-8a8a-1bd63704a566.png)

**Comment by JuliviMig** [comment]
закрытие  на  MT4  и  есть  открытие  в  противоположном  направлении.   Текст  поменял
