### ISSUE TITLE
Синхронизация при запуске и по кнопке

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Copyer#24]
Не включая копировщик,  открыть market order с  SL TP на master account. Включить копировщик.
- Подтвердить синхронизацию при входе.
- Отказаться от синхронизации при входе, дождаться запуска и нажать Sync all

**Нет синхронизации ни по кнопке, ни при запуске**

**Comment by JuliviMig** [comment]
изменил.  Но  еще  бы  погонять.  Там  еще  куча  вариантов
