### ISSUE TITLE
FIFO

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Copyer#25]
**Открыть** маркет ордера на 0.01, 0.02, 0.01, 0.02 лота так, чтобы время открытия отличалось на 0.5 - 1 мин.
Закрывать их в обратном порядке, т.е. первыми - самые новые

На slave account ордера должны закрываться в порядке создания по объемам, т.е. самые старые в данном объеме - в первую очередь

**Вместо того, чтобы закрывать самые старые в данном объеме, частично закрывает более новые**

**Comment by JuliviMig** [comment]
всегда  закрываются  самые  старые  не  обращая  внимания  на  объем.  Проверил

**Comment by RybasATgithub** [comment]
Исправлено в 2.2.5.123
