### ISSUE TITLE
Нет коннекта к некоторым счетам. На старой версии был

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Copyer#26]
OANDA-v20 Practice-1
Login 4518610
Password 8zhojol
Investor ugc6lbv

Pepperstone-Demo02
Login: 7703624 
Password: Hpin0s 

По srv файлам проверял - все IP, что надо. OANDA сильно нужна, твое FIFO проверить

**Comment by JuliviMig** [comment]
OANDA  работает, но проблемы  остались.

**Comment by JuliviMig** [comment]
переписал.  полегчало, но  тестировать  там  еще  есть  что
