### ISSUE TITLE
FIFO: закрытие ордеров

### ISSUE THREAD

**Issue by RybasATgithub** [JuliviMig/BJF_Copyer#9]
Только для FIFO.
Открываем на мастере, открывается на слейве.
Закрываем на слейве с закладки Orders - закрываются на слейве.
Можно закрывать и на терминала слейва - тот же эффект.
Закрываем на мастере из терминала - на слейве открываются встречные ордера.

Список ордеров мастера не отражает закрытия ордеров, т.е. они там остаются после закрытия.

**Comment by JuliviMig** [comment]
Только для FIFO.
Открываем на мастере, открывается на слейве.
Закрываем на слейве с закладки Orders - закрываются на слейве.
Можно закрывать и на терминала слейва - тот же эффект.
Закрываем на мастере из терминала - на слейве открываются встречные ордера.
    ////  Так  и  будет  -  нефиг  руками  лазить

Список ордеров мастера не отражает закрытия ордеров, т.е. они там остаются после закрытия.

   ///   Исправил
